### PR TITLE
FS2024 Initial support

### PR DESCRIPTION
**Pull request by iadarroch**

### CODE REVIEW

**Comment by iadarroch** [comment]
Hi @mpaperno. This is an initial implementation of support for FS2024. It does not include the new controller options or structure of FS2024, but should at least display a reasonable amount of settings. I have not created a release as yet, but hope to do so in the next few weeks. What install type do you have? Are you able to check the Steam options?

**Comment by mpaperno** [comment]
Hi Ian,

Nah, I just have the MS/Xbox Store version. I "rent" it with Game Pass, actually.

I just pulled this branch and gave it a quick test.  Seems to work... found my '24 profiles folder too.

Only apparent thing I noticed was that selecting just the "Assigned" bindings for the report still included all the un-assigned ones.  Presumably because the new '24 files seem to include the un-assigned ones as well....  strangely.
(What happens when they add new commands? Update all the user's binding files?  What could go wrong...)

Cheers,
-Max

**Comment by iadarroch** [comment]
@mpaperno Have had a thought to make it easier to compare FS2020 profiles with FS2024 - instead of selecting a specific install & version, allow the program to look for all combinations, and display all found profiles in the list. That way, you can compare a 2020 profile with the equivalent 2024 profile(s). This will hopefully help all the issues people are having with 2024 controller bindings.

**Comment by iadarroch** [comment]
The above commit is a work in progress. Initial support of side-by-side comparison of FS2020 and FS2024 bindings is working, but code and UI need tidying up before a release.

**Pull request merged**
